version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
     POSTGRES_DB: store_db
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: store
    container_name: store_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      db:
        condition: service_healthy

  worker:
    image: store
    container_name: store_worker
    command: /start-worker
    volumes:
     - ./:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  beat:
    image: store
    container_name: store_beat
    command: /start-beat
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    image: store
    container_name: store_flower
    command: /start-flower
    volumes:
      - ./:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
